lib/whackathon_platform_web/router.ex
defmodule WhackathonPlatformWeb.Router do
  use WhackathonPlatformWeb, :router
  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WhackathonPlatformWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Pow authentication
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  # PowAssent for github login
  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  scope "/" do
    pipe_through :browser

    pow_assent_routes()
    pow_extension_routes()
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout

    resources "/users", UserController, only: [:show] do
      resources "/projects", ProjectController, only: [:create, :show]
    end

    resources "/projects", ProjectController, only: [:index]
    resources "/events", EventController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WhackathonPlatformWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WhackathonPlatformWeb.Telemetry
      pow_routes()
    end
  end
end

lib/whackathon_platform/projects/project.ex
defmodule WhackathonPlatform.Project do
  use Ecto.Schema
  import Ecto.Changeset
  alias WhackathonPlatform.Users.User

  @primary_key {:id, :id, autogenerate: true}
  @foreign_key_type :id
  schema "projects" do
    field :description, :string
    field :title, :string
    field :github_link, :string
    belongs_to :user, User

    timestamps()
  end

  @doc """
  Creates a new Project struct
  """
  def new(attrs) do
    %__MODULE__{}
    |> changeset(attrs)
  end

  @doc """
  This documentation is to avoid unnecessary gotcha
  """
  def changeset(project, attrs \\ %{}) do
    project
    |> cast(attrs, [:title, :description, :user_id, :github_link])
    |> validate_required([:title, :description, :user_id])
  end
end

lib/whackathon_platform_web/controllers/project_controller.ex
defmodule WhackathonPlatformWeb.ProjectController do
  use WhackathonPlatformWeb, :controller

  alias WhackathonPlatform.Repo
  alias WhackathonPlatform.Project
  alias WhackathonPlatform.Users.User

  def index(conn, _params) do
    projects = Repo.all(Project)
    render(conn, "index.html", projects: projects)
  end

  def create(conn, %{"project" => project_params, "user_id" => user_id}) do
    title = project_params["title"]
    description = project_params["description"]
    github_link = project_params["github_link"]
    user = Repo.get!(User, user_id)
    project =
      Ecto.build_assoc(user, :projects, title: title, description: description, github_link: github_link)
      |> Project.changeset()
      |> Repo.insert()

    case project do
      {:ok, _project} ->
        conn
        |> redirect(to: Routes.user_path(conn, :show, user.username))
      {:error, changeset} ->
        conn
        |> assign(:project_changeset, changeset)
        |> redirect(to: Routes.user_path(conn, :show, user.username))
    end

    # conn
    # |> redirect(to: Routes.user_path(conn, :show, user.username))
  end
end

lib/whackathon_platform_web/views/project_view.ex
defmodule WhackathonPlatformWeb.ProjectView do
  use WhackathonPlatformWeb, :view
end

lib/whackathon_platform_web/templates/project/index.html.eex
<div class="absolute top-0 w-full h-full bg-top bg-cover" style="
            background-image: url('https://images.unsplash.com/photo-1579548122080-c35fd6820ecb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3450&q=80');
          ">
  <div class="flex flex-row text-black justify-center pt-20">
    <ul class="w-3/4">
      <%= for project <- @projects do %>
      <li class="pt-4">
          <div class="flex flex-col rounded-lg p-5 shadow-lg bg-gradient-to-tr from-black via-indigo-500 to-blue-500">
            <!-- Event name -->
            <div class="flex justify-center">
              <h1 class="font-bold text-4xl uppercase text-white"><%= project.title %></h1>
            </div>
            <div class="flex flex-row justify-between">
              <!-- theme -->
              <div class="py-5 text-white">
                <h2 class="font-bold text-xl uppercase">Description</h2>
                <h2 class="text-lg"><%= project.description %></h2>
              </div>
            </div>
          </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>

lib/whackathon_platform_web/templates/project/new.html.eex
<div class="flex flex-row text-black justify-center pt-20">
  <div
    class="flex flex-col rounded-lg p-5 shadow-lg w-3/12 items-center bg-gradient-to-tr from-black via-indigo-500 to-blue-500">
    <h1 class="text-4xl text-center">Add a new project</h1>

    <%= form_for @project_changeset, Routes.user_project_path(@conn, :create, @user), fn f -> %>
    <%= if @project_changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
    <% end %>

    <div>
      <%= label f, :title %>
      </br>
      <%= text_input f, :title, class: "rounded-md" %>
      <%= error_tag f, :title %>
    </div>

    <div>
      <%= label f, :description %>
      </br>
      <%= text_input f, :description, class: "rounded-md" %>
      <%= error_tag f, :description %>
    </div>

    <div>
      <%= label f, :github_link %>
      </br>
      <%= text_input f, :github_link, class: "rounded-md" %>
      <%= error_tag f, :github_link %>
    </div>

    <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-center p-5">
      <div class="rounded-md shadow">
        <%= submit "Submit", class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10" %>
      </div>
    </div>

    <% end %>

  </div>
</div>