lib/whackathon_platform_web/router.ex
defmodule WhackathonPlatformWeb.Router do
  use WhackathonPlatformWeb, :router
  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WhackathonPlatformWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Pow authentication
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  # PowAssent for github login
  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  scope "/" do
    pipe_through :browser

    pow_assent_routes()
    pow_extension_routes()
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout

    resources "/users", UserController, only: [:show] do
      resources "/projects", ProjectController, only: [:create, :show]
    end

    resources "/projects", ProjectController, only: [:index]
    resources "/events", EventController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WhackathonPlatformWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WhackathonPlatformWeb.Telemetry
      pow_routes()
    end
  end
end

lib/whackathon_platform_web/views/layout_view.ex
defmodule WhackathonPlatformWeb.LayoutView do
  use WhackathonPlatformWeb, :view
end

lib/whackathon_platform_web/templates/layout/app.html.eex
<main role="main">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/whackathon_platform_web/templates/layout/appnostyling.html.eex
<main role="main">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/whackathon_platform_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/whackathon_platform_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Whackathon Platform" %>
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&family=Tourney:ital@1&display=swap"
    rel="stylesheet">
</head>

<body>
  <!-- Navbar -->
  <nav class="top-0 absolute z-50 w-full flex flex-wrap items-center justify-between px-2 py-3 navbar-expand-lg">
    <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
      <div class="w-full relative flex justify-between lg:w-auto lg:static lg:block lg:justify-start">
        <a class="text-lg font-bold leading-relaxed inline-block mr-4 py-2 whitespace-no-wrap uppercase text-white"
          href=" <%= Routes.page_path(@conn, :index) %> ">Whackathon</a>
        <button
          class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none"
          type="button" onclick="toggleNavbar('example-collapse-navbar')">
          <i class="text-white fas fa-bars"></i>
        </button>
      </div>

      <div class="lg:flex flex-grow items-center bg-white lg:bg-transparent  hidden"
        id="example-collapse-navbar">
          <a
            class="ring-4 lg:ml-auto text-sm font-bold uppercase lg:text-white md:text-black border border-transparent lg:bg-indigo-600 lg:hover:bg-indigo-700 md:py-2 md:px-6 lg:rounded-full">
            <i class="hidden md:block far fa-calendar-alt"></i>
            <%= link "Events", to: Routes.event_path(@conn, :index) %>
          </a>
        <ul class="flex flex-col lg:flex-row list-none lg:ml-auto">
          <%= if @current_user do %>
          <li class="flex items-center">
            <a class=" text-lg font bold leading-relaxed whitespace-no-wrap px-3 py-1 text-white">
              <i class="lg:hidden text-black fas fa-user"></i>
              <%= link "Profile", to: Routes.user_path(@conn, :show, @current_user.username), class: "pr-5 text-black lg:text-white font-bold" %>
            </a>
          </li>
          <li class="flex items-center">
            <a class=" text-lg font bold leading-relaxed whitespace-no-wrap px-3 py-1 text-white">
              <i class="lg:hidden text-black fas fa-sign-out-alt"></i>
              <%= link "Sign out", to: Routes.logout_path(@conn, :delete), method: :delete, class: "pr-5 text-black lg:text-white font-bold" %>
            </a>
          </li>
          <% end %>
          <li class="flex items-center">
            <a target="_blank" rel="noopener noreferrer"
              class="lg:text-white lg:hover:text-gray-300 text-gray-800 px-3 py-4 lg:py-2 flex items-center text-xs uppercase font-bold"
              href="https://github.com/Antonfogelberg/whackathon-platform"><i
                class="text-black fab fa-github text-lg leading-lg"></i><span
                class="lg:hidden inline-block ml-2">Github</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%= @inner_content %>
</body>
<script>
  function toggleNavbar(collapseID) {
    document.getElementById(collapseID).classList.toggle("hidden");
    document.getElementById(collapseID).classList.toggle("block");
  }

  function modalLogin() {
    return {
      state: 'CLOSED',
      open() {
        this.state = 'Transition'
        setTimeOut(() => {
          this.state = 'OPEN'
        }, 50)
      },
      close() {
        this.state = 'TRANSITION'
        setTimeout(() => {
          this.state = 'CLOSED'
        }, 300)
      },
      isOpen() {
        return this.state === 'OPEN'
      },
      isOpening() {
        return this.state !== 'CLOSED'
      },
    }
  }
</script>

</html>