lib/whackathon_platform_web/router.ex
defmodule WhackathonPlatformWeb.Router do
  use WhackathonPlatformWeb, :router
  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WhackathonPlatformWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Pow authentication
  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  pipeline :not_authenticated do
    plug Pow.Plug.RequireNotAuthenticated,
      error_handler: WhackathonPlatformWeb.AuthErrorHandler
  end

  # PowAssent for github login
  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  scope "/" do
    pipe_through :browser

    pow_assent_routes()
    pow_extension_routes()
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :not_authenticated]

    get "/signup", RegistrationController, :new, as: :signup
    post "/signup", RegistrationController, :create, as: :signup
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
  end

  scope "/", WhackathonPlatformWeb do
    pipe_through [:browser, :protected]

    delete "/logout", SessionController, :delete, as: :logout

    resources "/users", UserController, only: [:show] do
      resources "/projects", ProjectController, only: [:create, :show]
    end

    resources "/projects", ProjectController, only: [:index]
    resources "/events", EventController
  end

  # Other scopes may use custom stacks.
  # scope "/api", WhackathonPlatformWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WhackathonPlatformWeb.Telemetry
      pow_routes()
    end
  end
end

lib/whackathon_platform_web/controllers/session_controller.ex
defmodule WhackathonPlatformWeb.SessionController do
  use WhackathonPlatformWeb, :controller

  def new(conn, _params) do
    changeset = Pow.Plug.change_user(conn)

    conn
    |> assign(:action, "/login")
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    conn
    |> assign(:action, "/login")
    |> Pow.Plug.authenticate_user(user_params)
    |> case do
      {:ok, conn} ->
        conn
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, conn} ->
        changeset = Pow.Plug.change_user(conn, conn.params["user"])

        conn
        |> put_flash(:info, "Invalid email or password")
        |> render("new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn
    |> Pow.Plug.delete()
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/whackathon_platform_web/views/pow/session_view.ex
defmodule WhackathonPlatformWeb.Pow.SessionView do
  use WhackathonPlatformWeb, :view
end

lib/whackathon_platform_web/views/session_view.ex
defmodule WhackathonPlatformWeb.SessionView do
  use WhackathonPlatformWeb, :view
end

lib/whackathon_platform_web/templates/session/new.html.eex
<div class="absolute top-0 w-full h-full bg-top bg-cover" style="
            background-image: url('https://images.unsplash.com/photo-1579548122080-c35fd6820ecb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3450&q=80');
          ">
  <div class="flex flex-row text-black justify-center pt-20">

    <div
      class="flex flex-col rounded-lg p-5 shadow-lg w-3/12 items-center bg-gradient-to-tr from-black via-indigo-500 to-blue-500">
      <h1 class="text-4xl text-center">Sign in</h1>
      </br>
      <%= form_for @changeset, @action, [as: :user], fn f -> %>
      <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
      <% end %>

      <div>
        <%= label f, Pow.Ecto.Schema.user_id_field(@changeset) %>
        </br>
        <%= text_input f, Pow.Ecto.Schema.user_id_field(@changeset), class: "rounded-md" %>
        <%= error_tag f, Pow.Ecto.Schema.user_id_field(@changeset) %>
      </div>

      <div>
        <%= label f, :password %>
        </br>
        <%= password_input f, :password, class: "rounded-md" %>
        <%= error_tag f, :password %>
      </div>

      <div class="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-center p-5">
        <div class="rounded-md shadow">
          <%= submit "Sign in", class: "w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 md:py-4 md:text-lg md:px-10" %>
        </div>
      </div>
      <% end %>

      <div class="flex flex-row justify-evenly min-w-full">
        <span><%= link "Register", to: Routes.signup_path(@conn, :new) %></span>
        |
        <span>
          <%= link "Forgot Password", to: Routes.pow_reset_password_reset_password_path(@conn, :new) %>
        </span>
        |
        <%= for link <- PowAssent.Phoenix.ViewHelpers.provider_links(@conn),
  do: content_tag(:span, link) %>
      </div>
    </div>
  </div>
</div>